require "net/http"
require "yaml"

# Regenerates config/age_grading.yml from the official WMA 2020 road tables.
#
# Source:  https://github.com/Runalyze/age-grade (MIT code, CC BY 4.0 tables)
# Upstream: https://github.com/AlanLyttonJones/Age-Grade-Tables (2020 Files)
namespace :age_grading do
  SOURCES = {
    "male"   => "https://raw.githubusercontent.com/Runalyze/age-grade/master/src/Table/MaleTable.php",
    "female" => "https://raw.githubusercontent.com/Runalyze/age-grade/master/src/Table/FemaleTable.php"
  }.freeze

  AGE_RANGE = (5..100) # AbstractTable::AgeRange; AgeFactors[0] is age 5

  # our COMMON_RACE_DISTANCES keys => official table distance value [km]
  DISTANCE_MAP = {
    "5.0"    => 5.0,
    "10.0"   => 10.0,
    "15.0"   => 15.0,
    "21.097" => 21.0975,
    "42.195" => 42.195,
    "50.0"   => 50.0,
    "100.0"  => 100.0
  }.freeze

  desc "Regenerate config/age_grading.yml from the official WMA 2020 tables"
  task :generate do
    standards = SOURCES.transform_values { |url| build_standards(Net::HTTP.get(URI(url))) }

    File.write(Rails.root.join("config", "age_grading.yml"), header + { "standards" => standards }.to_yaml.sub(/\A---\n/, ""))
    puts "Wrote config/age_grading.yml"
  end

  def self.build_standards(php)
    distances = flat_array(php, "Distances")
    open_std  = flat_array(php, "OpenStandard")
    factors   = factor_rows(php)

    DISTANCE_MAP.each_with_object({}) do |(key, value), result|
      index = distances.index { |d| (d - value).abs < 1e-6 } or raise "distance #{value} not found"

      result[key] = AGE_RANGE.each_with_object({}) do |age, ages|
        factor = factors[age - AGE_RANGE.begin][index]
        ages[age.to_s] = (open_std[index] / factor).round unless factor.nil? || factor.zero?
      end
    end
  end

  def self.flat_array(php, name)
    php.match(/\$#{name}\s*=\s*\[(.*?)\];/m)[1].scan(/-?\d+\.?\d*/).map(&:to_f)
  end

  def self.factor_rows(php)
    body = php.match(/\$AgeFactors\s*=\s*\[(.*)\];/m)[1]
    body.scan(/\[([^\[\]]*)\]/).map { |row| row[0].scan(/-?\d+\.?\d*/).map(&:to_f) }
  end

  def self.header
    <<~HDR
      # Age-grading standards (WMA 2020 road running tables).
      #
      # Auto-generated by `bin/rails age_grading:generate`. Each value is the age
      # standard in seconds = OpenStandard[distance] / AgeFactor[age][distance],
      # keyed standards[sex][distance_km][age]. Age-graded % = standard / time * 100.
      #
      # Source:   https://github.com/Runalyze/age-grade (MIT code, CC BY 4.0 tables)
      # Upstream: https://github.com/AlanLyttonJones/Age-Grade-Tables (2020 Files)
      #
      # Tables (c) WMA / Alan Jones, licensed CC BY 4.0.
    HDR
  end
end
